common:
  orchestrator_common:
    attributes:
      deployment_mode: simple
    task_uuid: deployment_task

  openstack_common:
   internal_virtual_ip: 10.0.0.127
   public_virtual_ip: 192.168.100.127
   create_networks: true
   fixed_range: 192.168.0.0/24
   floating_range: 192.168.100.0/24
   swift_loopback: loopback
   nv_physical_volumes:
    - /dev/vdb
   external_ip_info:
     public_net_router: 192.168.100.1
     ext_bridge: 192.168.100.15
     pool_start: 192.168.100.225
     pool_end: 192.168.100.239
   segment_range: 900:999
   network_manager: nova.network.manager.FlatDHCPManager
   auto_assign_floating_ip: true
   quantum_netnode_on_cnt: false
   use_syslog: true
   syslog_server: 192.168.100.12
   mirror_type: default
   quantum: false
   internal_interface: eth0
   public_interface: eth1
   private_interface: eth2
   public_netmask: 255.255.255.0
   internal_netmask: 255.255.255.0
   default_gateway: 192.168.100.1
   nagios_master: fuel-controller-01.default
   cinder: true
   cinder_nodes:
   - compute
   swift: true
   repo_proxy: http://10.0.0.100:3128
   deployment_id: '53'
   dns_nameservers:
   - 10.0.0.100
   - 8.8.8.8
   nodes:
   - name: fuel-cobbler
     role: cobbler
     internal_address: 10.0.0.100
     public_address: 192.168.100.100
   - name: fuel-controller-01
     role: primary-controller
     internal_address: 10.0.0.101
     public_address: 192.168.100.101
     swift_zone: 1
     mountpoints: 1 2\n 2 1
     storage_local_net_ip: 10.0.0.101
   - name: fuel-compute-01
     role: compute
     internal_address: 10.0.0.105
     public_address: 192.168.100.105

  cobbler_common:
    # for Centos
    # profile: "centos64_x86_64"
    # for Ubuntu
    profile: "ubuntu_1204_x86_64"
    netboot-enabled: "1"
    # for Ubuntu
    # ksmeta: "puppet_version=2.7.19-1puppetlabs2 \
    # for Centos
    name-servers: "10.0.0.100"
    name-servers-search: "default"
    gateway: 10.0.0.100
    ksmeta: "puppet_version=2.7.19-1puppetlabs2 \
      puppet_auto_setup=1 \
      puppet_master=fuel-pm.default \
      puppet_enable=0 \
      ntp_enable=1 \
      mco_auto_setup=1 \
      mco_pskey=un0aez2ei9eiGaequaey4loocohjuch4Ievu3shaeweeg5Uthi \
      mco_stomphost=10.0.0.100 \
      mco_stompport=61613 \
      mco_stompuser=mcollective \
      mco_stomppassword=AeN5mi5thahz2Aiveexo \
      mco_enable=1"


fuel-controller-01:
  hostname: "fuel-controller-01"
  role: controller
  interfaces:
    eth0:
      mac: "52:54:00:c5:ab:57"
      static: "1"
      ip-address: "10.0.0.101"
      netmask: "255.255.255.0"
      dns-name: "fuel-controller-01.default"
      management: "1"
    eth1:
      mac: "52:54:00:00:df:e8"
      static: "0"
    eth2:
      mac: "52:54:00:49:b6:19"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-compute-01:
  hostname: "fuel-compute-01"
  role: compute
  interfaces:
    eth0:
      mac: "52:54:00:70:f7:94"
      static: "1"
      ip-address: "10.0.0.105"
      netmask: "255.255.255.0"
      dns-name: "fuel-compute-01.default"
      management: "1"
    eth1:
      mac: "52:54:00:94:4e:39"
      static: "0"
    eth2:
      mac: "52:54:00:7d:cb:53"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-compute-01:
  hostname: "fuel-compute-01"
  role: compute
  interfaces:
    eth0:
      mac: "52:54:00:70:f7:94"
      static: "1"
      ip-address: "10.0.0.105"
      netmask: "255.255.255.0"
      dns-name: "fuel-compute-01.default"
      management: "1"
    eth1:
      mac: "52:54:00:94:4e:39"
      static: "0"
    eth2:
      mac: "52:54:00:7d:cb:53"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-compute-02:
  hostname: "fuel-compute-02"
  role: compute
  interfaces:
    eth0:
      mac: "52:54:00:70:f7:91"
      static: "1"
      ip-address: "10.0.0.106"
      netmask: "255.255.255.0"
      dns-name: "fuel-compute-02.default"
      management: "1"
    eth1:
      mac: "52:54:00:94:4e:31"
      static: "0"
    eth2:
      mac: "52:54:00:7d:cb:51"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

